spring.application.name=DocMind
spring.config.import=optional:file:.env[.properties]

# supabase postgres - now used only for users, refresh tokens and sessions not embeddings
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# pinecone credentials - used for storing embeddings
pinecone.api-key=${PINECONE_API_KEY}
pinecone.index-name=${PINECONE_INDEX_NAME}
pinecone.namespace=${PINECONE_NAMESPACE:default}


SECRET_KEY_BACKEND=${JWT_SECRET}

# using gemini model for response
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite
spring.ai.google.genai.streaming.enabled=true

# for getting embeddings currently using gemini may change it later
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.options.model=text-embedding-004

# File restrictions
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
