package com.accenture.intern.docmind.aiservices.understanding;

import java.util.List;
import java.util.UUID;

/**
 * Immutable blueprint generated by the Query Understanding stage for each incoming query.
 *
 * <p>{@code optimizedQuery} is the keyword-dense, concept-expanded version of the
 * original user question produced by the unified LLM router call. All retrieval
 * paths use this expanded form instead of the raw query so that abstract concepts
 * (e.g. "perseverance") are normalised to concrete keyword phrases that BM25 and
 * dense vectors can match. Falls back to the raw question if the router returns null.
 *
 * <p>{@code subQueries} is populated only for CONCEPT_EXPANSION — it contains
 * fully-formed action-oriented sub-queries for parallel fan-out retrieval.
 *
 * <p>{@code comparisons} is populated only for MULTI_SOURCE — one entry per
 * comparison entity, each carrying its own optimized_query.
 */
public record RetrievalPlan(
        String id,
        String purpose,
        Intent intent,
        Scope scope,
        RetrievalStrategy retrievalStrategy,
        RetrievalExecutionMode executionMode, // Added to explicitly decide execution mode
        List<ComparisonTarget> comparisons,
        List<String> subQueries,

        /**
         * Keyword-dense, vocabulary-normalised rewrite of the user's query.
         * Use this string for all vector-store and BM25 calls instead of the
         * raw user question.
         */
        String optimizedQuery,
        /**
         * The named entities extracted by the LLM from the query, paired with a confidence score.
         * Used for entity compatibility checking in Multi-Signal Ranking.
         */
        List<EntityResolution> entities,
        /**
         * Explicit filenames resolved from the user's references (e.g. "the first one", "all three").
         * Used to filter Pinecone vector search specifically to these documents.
         */
        List<String> targetDocuments
) {
    /** Backward-compatible constructor for callers that don't need multi-source/concept routing. */
    public RetrievalPlan(Intent intent, Scope scope) {
        this(UUID.randomUUID().toString(), "Primary Retrieval", intent, scope, RetrievalStrategy.SINGLE_SOURCE, RetrievalExecutionMode.WHOLE_DOCUMENT, List.of(), List.of(), null, List.of(), List.of());
    }

    /** Convenience constructor for non-retrieval fast-pass decisions (no optimizedQuery needed). */
    public RetrievalPlan(Intent intent, Scope scope, RetrievalStrategy strategy,
                         List<ComparisonTarget> comparisons, List<String> subQueries) {
        this(UUID.randomUUID().toString(), "Primary Retrieval", intent, scope, strategy, strategy == RetrievalStrategy.SINGLE_SOURCE ? RetrievalExecutionMode.WHOLE_DOCUMENT : RetrievalExecutionMode.RANKED_RETRIEVAL, comparisons, subQueries, null, List.of(), List.of());
    }

    /** Convenience constructor for MULTI_SOURCE */
    public RetrievalPlan(Intent intent, Scope scope, RetrievalStrategy strategy, List<ComparisonTarget> comparisons) {
        this(UUID.randomUUID().toString(), "Primary Retrieval", intent, scope, strategy, RetrievalExecutionMode.RANKED_RETRIEVAL, comparisons, List.of(), null, List.of(), List.of());
    }
    
    /** Convenience constructor for a standard unified router plan */
    public RetrievalPlan(Intent intent, Scope scope, RetrievalStrategy strategy, RetrievalExecutionMode executionMode, 
                         List<ComparisonTarget> comparisons, List<String> subQueries, String optimizedQuery, 
                         List<EntityResolution> entities, List<String> targetDocuments) {
        this(UUID.randomUUID().toString(), "Primary Retrieval", intent, scope, strategy, executionMode, comparisons, subQueries, optimizedQuery, entities, targetDocuments);
    }
}
